Date - 01/02/2022

# Tensorflow Basics - 1 

## Topics in Deep Learning Lab


### Name : Abhishek Aditya BS
### SRN  : PES1UG19CS019
### Semester & Section : VI Sem & A Section

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.7.0


 # Creating a Tensor

 Rank - 1 Tensor
 Constant Tensors are Immuatable

In [ ]:
rank1_tensor = tf.constant([0,1,43,2,3,4,8,13,21])
print(rank1_tensor)

tf.Tensor([ 0  1 43  2  3  4  8 13 21], shape=(9,), dtype=int32)


# Representing Scalar

Scalar can be represented as rank-0 Tensor

In [ ]:
scalar = tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


# Rank-2 Tensors (nested lists)

In [ ]:
rank2_tensor = tf.constant([[1,2,3], [4,5,6]])
print(rank2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Defining with Type

By default type is inferred by tensorflow based on input

### Supported Types

- float16, float32, float64
- int8, int16, int32, int64
- uint8, uint16 (unsigned)
- string
- bool
- complex64, complex128
- qint8, qint32(quantized)

In [ ]:
rank2_tensorfloat = tf.constant([[1,2], [3,4], [5,6]], dtype=tf.float32)
print(rank2_tensorfloat)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


# Attributes / Properties of Tensors

In [ ]:
print(f'Tensor Shape : {rank2_tensor.shape}')
print(f'Tensor Rank : {rank2_tensor.ndim}')
print(f'Type of all elements : {rank2_tensor.dtype}')
print(f'Total Number of elements : {tf.size(rank2_tensor.shape)}')


Tensor Shape : (2, 3)
Tensor Rank : 2
Type of all elements : <dtype: 'int32'>
Total Number of elements : 2


# Interoperability with NumPy

In [ ]:
import numpy as np

In [ ]:
np_arr = np.array(rank2_tensor)
np_arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
np_arr = rank2_tensor.numpy()
np_arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Converting Numpy array to Tensor

In [ ]:
np_arr = np.array([[1,2,3],[4,5,6]])
tensor_frm_np = tf.constant(np_arr)
print(tensor_frm_np)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


# Indexing Tensors

In [ ]:
print('Tensor :', rank1_tensor)
print('Index 2 :', rank1_tensor[2])
print('Index 4 :', rank1_tensor[4])

Tensor : tf.Tensor([ 0  1 43  2  3  4  8 13 21], shape=(9,), dtype=int32)
Index 2 : tf.Tensor(43, shape=(), dtype=int32)
Index 4 : tf.Tensor(3, shape=(), dtype=int32)


# Slicing Tensors

In [ ]:
print('Slicing 3-6 (including 3, excluding 6) : ', rank1_tensor[3:6])
print('Slicing with step(2) : ', rank1_tensor[3:8:2])
print('All elements : ', rank1_tensor[:])
print('From Start of Tensor : ', rank1_tensor[:4])
print('To end of the tensor : ', rank1_tensor[4:])

Slicing 3-6 (including 3, excluding 6) :  tf.Tensor([2 3 4], shape=(3,), dtype=int32)
Slicing with step(2) :  tf.Tensor([ 2  4 13], shape=(3,), dtype=int32)
All elements :  tf.Tensor([ 0  1 43  2  3  4  8 13 21], shape=(9,), dtype=int32)
From Start of Tensor :  tf.Tensor([ 0  1 43  2], shape=(4,), dtype=int32)
To end of the tensor :  tf.Tensor([ 3  4  8 13 21], shape=(5,), dtype=int32)


# Multi Indexing Tensors

In [ ]:
print('Tensor :' , rank2_tensor)
print('Specific element: ', rank2_tensor[1][2])
print('Specific elumunt with "," operator: ', rank2_tensor[1, 2])
print('Slicing across different axes : ', rank2_tensor[1:, :])

Tensor : tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Specific element:  tf.Tensor(6, shape=(), dtype=int32)
Specific elumunt with "," operator:  tf.Tensor(6, shape=(), dtype=int32)
Slicing across different axes :  tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)
