In [1]:
import numpy as np
import pandas as pd

In [2]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [3]:
np.zeros((2,3),dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.random.rand(2,2,3)

array([[[0.03636432, 0.94773226, 0.91022875],
        [0.97497261, 0.85517602, 0.27414276]],

       [[0.5273971 , 0.14312515, 0.22112065],
        [0.02844663, 0.26606161, 0.50867587]]])

In [5]:
np.random.rand()

0.3903379689351213

In [6]:
np.random.seed(0)
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [7]:
np.random.seed(0)
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [8]:
x=[1,2,3]
a=np.array(x)
a

array([1, 2, 3])

In [9]:
x=[[1,2,3],[2,3,5]]
a=np.array(x)
a[1,2]

5

In [10]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[9,10,11],[54,87,90]])
c=np.multiply(a,b)
c          

array([[  9,  20,  33],
       [270, 522, 630]])

In [11]:
b=np.array([[2,6,8],[6,8,0],[3,5,11]])
c=np.matmul(a,b)
c

array([[ 23,  37,  41],
       [ 67, 113, 117]])

In [12]:
a=np.array([1,2])
b=np.array([4,6])
c=np.dot(a,b)
c

16

In [13]:
x=np.array([1,2])
y=np.array([7,90,89])
c=np.cross(x,y)
c

array([178, -89,  76])

In [14]:
x=np.array([[1,2],[89,900]])
inverse=np.linalg.inv(x)
inverse

array([[ 1.2465374 , -0.00277008],
       [-0.1232687 ,  0.00138504]])

In [15]:
t=np.transpose(x)
t

array([[  1,  89],
       [  2, 900]])

In [16]:
det=np.linalg.det(x)
det

721.9999999999998

In [17]:
x.shape

(2, 2)

In [18]:
df=pd.read_csv("example.csv")

In [19]:
print(df)

    SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C


In [20]:
print(list(df.columns))

['SL.No', 'Attribute A', 'Attribute B', 'Attribute C']


In [21]:
print(list(df['SL.No']))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [22]:
print(list(df.iloc[1]))

[2, nan, 22, 'B']


In [23]:
print(list(df.iloc[:,1]))

[12.0, nan, 31.0, 19.0, 22.0, nan, 41.0, 22.0, 90.0, 81.0, nan, 56.0, 33.0, 21.0, 78.0]


In [24]:
print(df[0:2])

   SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
1      2          NaN           22           B


In [25]:
print(df.mean(axis=0,skipna=True))

SL.No           8.000000
Attribute A    42.166667
Attribute B    31.733333
dtype: float64


In [26]:
g=df.groupby(by='Attribute A')

In [27]:
for grp, grpdata in g:
    print(grp,grpdata)

12.0    SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
19.0    SL.No  Attribute A  Attribute B Attribute C
3      4         19.0           13           C
21.0     SL.No  Attribute A  Attribute B Attribute C
13     14         21.0           12           C
22.0    SL.No  Attribute A  Attribute B Attribute C
4      5         22.0           24           A
7      8         22.0           78           B
31.0    SL.No  Attribute A  Attribute B Attribute C
2      3         31.0           13           A
33.0     SL.No  Attribute A  Attribute B Attribute C
12     13         33.0           67           A
41.0    SL.No  Attribute A  Attribute B Attribute C
6      7         41.0           21           C
56.0     SL.No  Attribute A  Attribute B Attribute C
11     12         56.0           35           C
78.0     SL.No  Attribute A  Attribute B Attribute C
14     15         78.0           14           C
81.0    SL.No  Attribute A  Attribute B Attribute C
9 

In [28]:
print(df)

    SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C


In [29]:
df.fillna(method="ffill",inplace=True)

In [30]:
df

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         12.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         22.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21           B
9      10         81.0           45           B
10     11         81.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [31]:
def create_numpy_ones_array(shape):
	#return a numpy array with one at all index
	array=None
	array=np.ones(shape)
	return array

In [32]:
create_numpy_ones_array((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
def create_numpy_zeros_array(shape):
	#return a numpy array with zeros at all index
	array=None
	array=np.zeros(shape)
	return array

In [35]:
create_numpy_zeros_array((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])